[green_agent]
agentbeats_id = ""
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}", NEBIUS_API_KEY = "${NEBIUS_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "agent"
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}", NEBIUS_API_KEY = "${NEBIUS_API_KEY}"}

[config]
# Add your assessment config here
